import { z } from 'zod'

export const PostSchema = z
  .object({
    title: z.string().min(1, 'Title is required').max(255, 'Title is too long'),
    content: z.string().optional(),
    attchments: z.array(z.string().url()).optional(), // Ensuring valid URLs for attachments
    forumId: z.number().int().positive('Invalid forum ID'),
    createdAt: z.date().optional(), // Auto-generated by Prisma
    updatedAt: z.date().optional(), // Auto-updated by Prisma
  })
  .strict()

export const PostUpdateSchema = z
  .object({
    title: z.string().min(1, 'Title is required').max(255, 'Title is too long'),
    content: z.string().optional(),
    attchments: z.array(z.string().url()).optional(), // Ensuring valid URLs for attachments
    createdAt: z.date().optional(), // Auto-generated by Prisma
    updatedAt: z.date().optional(), // Auto-updated by Prisma
  })
  .strict()
